FROM node:22-alpine AS build
RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev git bash
WORKDIR /opt/app
COPY package.json ./
RUN npm install
COPY . .
ENV NODE_ENV=production
RUN npm run build

FROM node:22-alpine AS runner
RUN apk add --no-cache vips
WORKDIR /opt/app
ENV NODE_ENV=production
COPY --from=build /opt/app /opt/app
EXPOSE 1337
CMD ["npm","run","start"]
